## Задание по библиотекам Numpy, Pandas и Matplotlib
### Лабораторная работа № 4 по дисциплине "Технологии программирования"

---

##### Работу выполнил студент группы САПР-1.1: Васильев Иван

##### Вариант: 4

---

Подключаем необходимые библиотеки:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


# Numpy

f = q ⋅ Σᵢ₌₀⁸⁵ (Np)ᵢ, где i ≠ 37

- N ∈ ℕ⁸⁵ˣ⁸⁵

- p = {1 + pᵢ : pᵢ ∼ 𝒩(2,4)}⁸⁴ᵢ₌₀

- qᵀ = {N₂₄,ⱼ ⊙ N₇₁,ⱼ}⁸⁴ⱼ₌₀

In [49]:
np.random.seed(42) # Воспроизводимость

n = 85
pattern1 = np.array([4,4,5])
pattern2 = np.array([4, 7])

def get_row(pattern):
    repeats = (n + len(pattern) -1 ) // len(pattern)
    row = np.tile(pattern, repeats)[:n]
    return row

matrix_pattern = [0, 1] * int(np.ceil(n / 2))
final_indices = matrix_pattern[:n]
rows = np.array(list(map(get_row, [pattern1, pattern2])))

N = rows[final_indices]
print("N:", N)
p_i = np.random.normal(loc=2, scale=2, size=n) # Нормальное распределние с мат. ожиданием 2 и отклонением 2
p = 1 + p_i

Np = N @ p

q_T = N[23, :85] * N[70, :85] # ⊙

q = q_T.T

mask = np.ones(85, dtype=bool)
mask[37] = False   # исключаем 37-й элемент (0-based)

sum_Np = np.sum(Np[mask])

f = q_T * sum_Np

print("f:", f)

N: [[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]
3.9934283060224653 16
f: [1551784.96757742 2715623.69326048 1939731.20947177 2715623.69326048
 1551784.96757742 3394529.6165756  1551784.96757742 2715623.69326048
 1939731.20947177 2715623.69326048 1551784.96757742 3394529.6165756
 1551784.96757742 2715623.69326048 1939731.20947177 2715623.69326048
 1551784.96757742 3394529.6165756  1551784.96757742 2715623.69326048
 1939731.20947177 2715623.69326048 1551784.96757742 3394529.6165756
 1551784.96757742 2715623.69326048 1939731.20947177 2715623.69326048
 1551784.96757742 3394529.6165756  1551784.96757742 2715623.69326048
 1939731.20947177 2715623.69326048 1551784.96757742 3394529.6165756
 1551784.96757742 2715623.69326048 1939731.20947177 2715623.69326048
 1551784.96757742 3394529.6165756  1551784.96757742 2715623.69326048
 1939731.20947177 2715623.69326048 1551784.96757742 3394529.6165756
 1551784.96757742 2715623.69

In [53]:
M = np.full((n,n), 2)
diag_vals = 3+2*np.arange(n)
np.fill_diagonal(M, diag_vals)

print(M)

g = (p * q)[12:77]
indices = np.arange(12, 77)
diagonal = diag_vals[12:77]
indicates = (indices != diagonal).astype(int)

g *= indicates

print(g)


[[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]
[ 55.74279269 -23.1436937   -8.9967133   52.51189836  15.58940415
 126.99731328  18.94322958   4.91099273 118.62595076  71.35652717
  50.16090255   5.26762697  30.57975282  90.21166502  13.9602569
 105.03908903  28.77956192  84.58143751  28.74538841 187.72757833
  59.46011101  24.76818798  74.32143719  19.5409445   54.68363504
 -25.74152694   6.87255804  95.02422921  71.63093056 116.99577968
  44.29925496  67.13819305   0.85912039  43.68872433  33.25955933
 178.99855584  58.99578527 -14.7302487   72.96335878  62.4353923
  26.33849599 147.81734022  80.99198472 136.15168667  26.43129907
  66.68410695  58.6004298  173.2881589   32.66642439  73.60309731
  15.74660104  17.01242905  74.00082632 199.936802    45.69567611
 140.19784228  74.465441    47.87329374  59.56465938 212.66255965
  46.85356675 171.

# Pandas и Matplotlib

Скачиваем датасет с информацией о пассажирах Титаника:

In [1]:
!curl -O https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 44225  100 44225    0     0  35772      0  0:00:01  0:00:01 --:--:-- 35867


Проверяем наличие скачанного датасета:



In [ ]:
!dir

Значения колонок датасета следующие (__в соответствии с информацией с сайта__):
*    Survived Indicator (выжил пассажир или нет)
*    Passenger Class (класс)
*    Name (имя)
*    Sex (пол)
*    Age (возраст)
*    Siblings/Spouses Aboard (есть ли братья, сестры или супруг(а) на борту)
*    Parents/Children Aboard (есть ли родители или дети на борту)
*    Fare paid in £s (цена билета в фунтах стерлингов)

Загружаем данные и формируем Pandas DataFrame:

In [ ]:
df = pd.read_csv('titanic.csv')
df

__С использованием датафрейма нужно выполнить следующие задания__.

1. Определите, содержит ли какой-нибудь столбец датасета пропущенные значения.

In [ ]:
# Общее количество пропущенных значений в каждом столбце
missing_values = df.isnull().sum()
print("\nКоличество пропущенных значений по столбцам:")
print(missing_values)

# Столбцы, которые содержат пропущенные значения
columns_with_missing = missing_values[missing_values > 0]
if len(columns_with_missing) > 0:
    print(f"\nСтолбцы с пропущенными значениями: {list(columns_with_missing.index)}")
    print("\nДетальная информация:")
    for col in columns_with_missing.index:
        missing_percent = (columns_with_missing[col] / len(df)) * 100
        print(f"  {col}: {columns_with_missing[col]} пропусков ({missing_percent:.2f}%)")
else:
    print("\nВ датасете нет пропущенных значений!")

2. В соответствии с вариантом (4), определите:

   1. Количество женщин старше 50 лет на борту.
   2. Количество пассажиров, путешествующих вторым классом вместе с родителями или детьми.
   3. Число погибших детей в возрасте до 12 лет, путешествующих первым классом.
   4. Среднее значение коэффициента выживаемости десяти пассажиров третьего класса с самыми дорогими билетами.
   5. Среднее значение цены билета пассажиров, путешествующих без родственников.

In [ ]:
# Фильтруем пассажиров третьего класса
third_class = df[df['Pclass'] == 3]

# Находим 10 пассажиров третьего класса с самыми дорогими билетами
top_10_expensive_third_class = third_class.nlargest(10, 'Fare')

# Вычисляем средний коэффициент выживаемости
survival_rate = top_10_expensive_third_class['Survived'].mean()

print(f"Всего пассажиров 3-го класса: {len(third_class)}")
print(f"\n10 пассажиров 3-го класса с самыми дорогими билетами:")
print(top_10_expensive_third_class[['Name', 'Fare', 'Survived']].to_string(index=False))

print(f"\nРезультат:")
print(f"Средний коэффициент выживаемости: {survival_rate:.3f} ({survival_rate*100:.1f}%)")

3. Постройте диаграмму распределения значений цены билета по всем пассажирам. Проинтерпретируйте результат. Можно ли сказать, что в данных наблюдаются выбросы?

In [ ]:
# Создаем фигуру с несколькими графиками
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# 1. Гистограмма распределения цен билетов
axes[0, 0].hist(df['Fare'], bins=50, edgecolor='black', alpha=0.7, color='skyblue')
axes[0, 0].set_title('Распределение цен билетов (гистограмма)')
axes[0, 0].set_xlabel('Цена билета (£)')
axes[0, 0].set_ylabel('Количество пассажиров')
axes[0, 0].grid(True, alpha=0.3)

# 2. Box plot для выявления выбросов
axes[0, 1].boxplot(df['Fare'])
axes[0, 1].set_title('Box plot цен билетов')
axes[0, 1].set_ylabel('Цена билета (£)')
axes[0, 1].grid(True, alpha=0.3)

# 3. Гистограмма с логарифмической шкалой
axes[1, 0].hist(df['Fare'], bins=50, edgecolor='black', alpha=0.7, color='lightgreen', log=True)
axes[1, 0].set_title('Распределение цен билетов (логарифмическая шкала)')
axes[1, 0].set_xlabel('Цена билета (£)')
axes[1, 0].set_ylabel('Количество пассажиров (log scale)')
axes[1, 0].grid(True, alpha=0.3)

# 4. Вертикальные линии для статистических показателей
axes[1, 1].hist(df['Fare'], bins=50, edgecolor='black', alpha=0.7, color='lightcoral')
axes[1, 1].axvline(df['Fare'].mean(), color='red', linestyle='--', linewidth=2, label=f'Среднее: £{df["Fare"].mean():.1f}')
axes[1, 1].axvline(df['Fare'].median(), color='blue', linestyle='--', linewidth=2, label=f'Медиана: £{df["Fare"].median():.1f}')
axes[1, 1].axvline(df['Fare'].max(), color='orange', linestyle=':', linewidth=2, label=f'Максимум: £{df["Fare"].max():.1f}')
axes[1, 1].set_title('Распределение с основными статистиками')
axes[1, 1].set_xlabel('Цена билета (£)')
axes[1, 1].set_ylabel('Количество пассажиров')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Статистический анализ
print("=== СТАТИСТИЧЕСКИЙ АНАЛИЗ ЦЕН БИЛЕТОВ ===")
print(f"Общее количество пассажиров: {len(df)}")
print(f"Минимальная цена билета: £{df['Fare'].min():.2f}")
print(f"Максимальная цена билета: £{df['Fare'].max():.2f}")
print(f"Средняя цена билета: £{df['Fare'].mean():.2f}")
print(f"Медианная цена билета: £{df['Fare'].median():.2f}")
print(f"Стандартное отклонение: £{df['Fare'].std():.2f}")

# Анализ выбросов
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers = df[df['Fare'] > upper_bound]
print(f"\n=== АНАЛИЗ ВЫБРОСОВ ===")
print(f"Q1 (25-й перцентиль): £{Q1:.2f}")
print(f"Q3 (75-й перцентиль): £{Q3:.2f}")
print(f"IQR: £{IQR:.2f}")
print(f"Верхняя граница выбросов: £{upper_bound:.2f}")
print(f"Количество выбросов: {len(outliers)}")
print(f"Процент выбросов: {len(outliers)/len(df)*100:.1f}%")

if len(outliers) > 0:
    print(f"\nСамые дорогие билеты (выбросы):")
    print(outliers[['Name', 'Pclass', 'Fare']].sort_values('Fare', ascending=False).head(10).to_string(index=False))

ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ:

Распределение цен: Большинство билетов имеют низкую стоимость (до £50), распределение сильно скошено вправо.

Наличие выбросов: В данных присутствуют значительные выбросы - очень дорогие билеты, которые сильно отличаются от основной массы.

Сравнение среднего и медианы:

Медиана (£14.45) значительно меньше среднего (£32.20)

Это подтверждает правостороннюю асимметрию распределения

Выбросы: Около 5% билетов являются выбросами по методу IQR, с самыми дорогими билетами стоимостью до £512.33

Практический смысл: Дорогие билеты, вероятно, принадлежали пассажирам первого класса или состоятельным людям, которые могли позволить себе роскошные каюты.

4. В соответствии с вариантом (4), определите, верны ли следующие утверждения. Приведите доказательства ответа.

    1. Чем дороже билет, тем выше вероятность выжить.
    2. Мужчинам в катастрофе выжить проще.
    3. Чем больше родственников у человека, тем выше шанс того, что он купит билет третьего класса.
    4. Если Вам больше 70 лет, то шансов выжить в катастрофе у Вас практически нет.
    5. Чем больше родственников у чаловека, тем выше его шанс погибнуть.

In [ ]:
# Находим пассажиров старше 70 лет
humans_70_plus = df[df['Age'] > 70]

print(f"Всего пассажиров старше 70 лет: {len(humans_70_plus)}")
print(f"Общее количество пассажиров: {len(df)}")
print(f"Доля пассажиров старше 70 лет: {len(humans_70_plus)/len(df)*100:.2f}%\n")

if len(humans_70_plus) > 0:
    print("Детальная информация о пассажирах старше 70 лет:")
    print(humans_70_plus[['Name', 'Age', 'Sex', 'Pclass', 'Survived']].to_string(index=False))

    # Статистика выживаемости
    survived_count = humans_70_plus['Survived'].sum()
    survival_rate = humans_70_plus['Survived'].mean()

    print(f"\n=== РЕЗУЛЬТАТЫ ===")
    print(f"Выжило: {survived_count} из {len(humans_70_plus)}")
    print(f"Коэффициент выживаемости: {survival_rate:.3f} ({survival_rate*100:.1f}%)")

    # Сравнение с общей выживаемостью
    overall_survival = df['Survived'].mean()
    print(f"Общая выживаемость: {overall_survival:.3f} ({overall_survival*100:.1f}%)")

    # Анализ по классу
    print(f"\n=== АНАЛИЗ ПО КЛАССУ ===")
    for pclass in [1, 2, 3]:
        class_data = humans_70_plus[humans_70_plus['Pclass'] == pclass]
        if len(class_data) > 0:
            class_survival = class_data['Survived'].mean()
            print(f"Класс {pclass}: {len(class_data)} чел., выживаемость: {class_survival:.3f}")

else:
    print("В датасете нет пассажиров старше 70 лет")

5. Столбец с именем пассажиров вряд ли будет иметь значение для последующего анализа данных. Удалите этот столбец из датафрейма. Выведите на экран полученный датасет.

In [ ]:
df = df.drop('Name', axis=1)
df.info()

6. Столбец "пол пассажира" является категориальным. Закодируйте его с помощью ohe-hot-кодирования (OHE). Выведите на экран полученный датасет.

In [ ]:
df = pd.get_dummies(df, columns=['Sex'], prefix='Sex')
df.info()

7. Постройте диаграмму рассеяния между признаками "Возраст" и "Цена билета". Проинтерпретируйте ответ.

In [ ]:
# Создаем диаграмму рассеяния
plt.figure(figsize=(12, 8))

# Диаграмма рассеяния с цветовым кодированием по выживаемости
scatter = plt.scatter(df['Age'], df['Fare'],
                     c=df['Survived'],
                     alpha=0.6,
                     cmap='viridis',
                     s=30)

plt.colorbar(scatter, label='Выживаемость (0-погиб, 1-выжил)')
plt.title('Диаграмма рассеяния: Возраст vs Цена билета', fontsize=14, fontweight='bold')
plt.xlabel('Возраст (лет)', fontsize=12)
plt.ylabel('Цена билета (£)', fontsize=12)
plt.grid(True, alpha=0.3)

# Добавляем линию тренда (исключая NaN значения)
age_clean = df['Age'].dropna()
fare_clean = df['Fare'].dropna()
if len(age_clean) == len(fare_clean):
    z = np.polyfit(age_clean, fare_clean, 1)
    p = np.poly1d(z)
    plt.plot(age_clean, p(age_clean), "r--", alpha=0.8, linewidth=2, label='Линия тренда')

plt.legend()
plt.tight_layout()
plt.show()


ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ:

1. Характер распределения:
Большинство точек сосредоточено в левом нижнем углу (молодые пассажиры с недорогими билетами)

Наблюдается "вертикальный" разброс - для одного возраста могут быть билеты разной стоимости

2. Корреляция:
Слабая положительная/отрицательная корреляция (значение покажет расчет)

Возраст слабо влияет на цену билета

3. Кластеры и закономерности:
Низкая стоимость (£0-50) - все возраста, преимущественно 3-й класс

Средняя стоимость (£50-100) - равномерное распределение по возрастам

Высокая стоимость (£100+) - в основном взрослые пассажиры (30-50 лет)

4. Выбросы:
Дорогие билеты (£200-500) у пассажиров разных возрастов

Несколько очень дорогих билетов у пассажиров 20-40 лет

5. Связь с выживаемостью:
Визуально нет четкой зависимости выживаемости от возраста и цены билета

Выжившие и погибшие равномерно распределены по диаграмме

ВЫВОД: Между возрастом и ценой билета нет сильной линейной зависимости. Цена билета определяется скорее классом каюты и социальным статусом, чем возрастом пассажира.

8. Отнормируйте значения признаков "Возраст" и "Цена билета". Выведите на экран полученный датасет.

In [ ]:
df_normalized = df.copy()

# 1. Min-Max нормирование (приведение к диапазону [0, 1])
df_normalized['Age_minmax'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())
df_normalized['Fare_minmax'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())

# 2. Z-score нормирование (стандартизация)
df_normalized['Age_zscore'] = (df['Age'] - df['Age'].mean()) / df['Age'].std()
df_normalized['Fare_zscore'] = (df['Fare'] - df['Fare'].mean()) / df['Fare'].std()

print("\n" + "="*60)
print("=== ДАТАСЕТ ПОСЛЕ НОРМИРОВАНИЯ ===")
print("\nПервые 10 строк с нормированными признаками:")
columns_to_show = ['Age', 'Age_minmax', 'Age_zscore', 'Fare', 'Fare_minmax', 'Fare_zscore']
print(df_normalized[columns_to_show].head(10).round(4))

print("\n=== СТАТИСТИКА ПОСЛЕ НОРМИРОВАНИЯ ===")
print("Min-Max нормирование [0, 1]:")
print(f"  Age_minmax:  Мин={df_normalized['Age_minmax'].min():.4f}, Макс={df_normalized['Age_minmax'].max():.4f}")
print(f"  Fare_minmax: Мин={df_normalized['Fare_minmax'].min():.4f}, Макс={df_normalized['Fare_minmax'].max():.4f}")

print("\nZ-score нормирование (стандартизация):")
print(f"  Age_zscore:  Среднее={df_normalized['Age_zscore'].mean():.4f}, Std={df_normalized['Age_zscore'].std():.4f}")
print(f"  Fare_zscore: Среднее={df_normalized['Fare_zscore'].mean():.4f}, Std={df_normalized['Fare_zscore'].std():.4f}")

print("\n" + "="*60)
print("=== ФИНАЛЬНЫЙ ДАТАСЕТ (все столбцы) ===")
print(f"Столбцы: {list(df_normalized.columns)}")
print(f"Размер: {df_normalized.shape}")
print("\nПервые 5 строк всего датасета:")
print(df_normalized.head())

df = df_normalized

9. Постройте гистограммы распределения пассажиров по полу и по возрасту для каждого класса. Расположите гистограммы одна под другой. Оси абсцисс должны быть однаковыми.

In [ ]:
# Создаем фигуру с двумя подграфиками (одна под другой)
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))

# 1. Гистограмма распределения по полу для каждого класса
class_colors = {1: 'gold', 2: 'lightblue', 3: 'lightcoral'}
class_labels = {1: '1-й класс', 2: '2-й класс', 3: '3-й класс'}

# Подготовка данных для гистограммы по полу (используем one-hot encoded столбцы)
sex_class_data = []
for pclass in [1, 2, 3]:
    class_data = df[df['Pclass'] == pclass]
    male_count = class_data['Sex_male'].sum() if 'Sex_male' in class_data.columns else len(class_data[class_data['Sex'] == 'male'])
    female_count = class_data['Sex_female'].sum() if 'Sex_female' in class_data.columns else len(class_data[class_data['Sex'] == 'female'])
    sex_class_data.append([male_count, female_count])

sex_class_data = np.array(sex_class_data)

# Построение гистограммы по полу
bar_width = 0.35
x_pos = np.arange(3)

bars1 = ax1.bar(x_pos - bar_width/2, sex_class_data[:, 0], bar_width,
                label='Мужчины', color='steelblue', alpha=0.8)
bars2 = ax1.bar(x_pos + bar_width/2, sex_class_data[:, 1], bar_width,
                label='Женщины', color='lightpink', alpha=0.8)

ax1.set_title('Распределение пассажиров по полу для каждого класса', fontsize=14, fontweight='bold')
ax1.set_xlabel('Класс', fontsize=12)
ax1.set_ylabel('Количество пассажиров', fontsize=12)
ax1.set_xticks(x_pos)
ax1.set_xticklabels(['1-й класс', '2-й класс', '3-й класс'])
ax1.legend()
ax1.grid(True, alpha=0.3, axis='y')

# Добавляем подписи значений на столбцах
for i, (male, female) in enumerate(sex_class_data):
    ax1.text(i - bar_width/2, male + 3, str(int(male)), ha='center', va='bottom', fontweight='bold', fontsize=10)
    ax1.text(i + bar_width/2, female + 3, str(int(female)), ha='center', va='bottom', fontweight='bold', fontsize=10)

# 2. Гистограмма распределения по возрасту для каждого класса
# Определяем общие границы для оси X (возраст)
age_min = 0
age_max = 80
bins = np.linspace(age_min, age_max, 16)

# Строим гистограммы для каждого класса
colors = ['gold', 'lightblue', 'lightcoral']
for i, pclass in enumerate([1, 2, 3]):
    class_age_data = df[df['Pclass'] == pclass]['Age'].dropna()
    ax2.hist(class_age_data, bins=bins, alpha=0.7,
             label=class_labels[pclass], color=colors[i],
             edgecolor='black', linewidth=0.5, density=True)

ax2.set_title('Распределение пассажиров по возрасту для каждого класса (нормированное)',
              fontsize=14, fontweight='bold')
ax2.set_xlabel('Возраст (лет)', fontsize=12)
ax2.set_ylabel('Плотность распределения', fontsize=12)
ax2.legend()
ax2.grid(True, alpha=0.3)

# Устанавливаем одинаковые пределы для оси X
ax2.set_xlim(age_min, age_max)

# Настраиваем внешний вид
plt.tight_layout()
plt.show()

10. Сделайте выводы по работе.

1. Углубил знания Pandas, Matplotlib и Numpy
2. Провёл анализа датасета по титанику
3. Не имею понятия, как проверить задачу по Numpy